### ISSUE TITLE
[Bug] - Installation broken after updating to new release

### ISSUE THREAD

**Issue by Laffarli** [Codeminer42/cm42-central#400]
Hello,

After updating to the new version (commit e6741f12a96b9a6fabbe2cb8205008fb22cfc91e), everything seems to be broken.
- Create story
- Update story
- Move story
- ...

Here errors we can find in debug console :
- pusherSockets.js:5 Uncaught TypeError: Cannot read property 'match' of undefined
    at a (pusherSockets.js:5)
- Uncaught TypeError: Cannot read property 'newStory' of undefined
    at HTMLButtonElement.<anonymous> (global_listeners.js:28)
- story_view.js:617 Uncaught TypeError: Cannot read property 'usernames' of undefined
    at N.i.t [as renderDescription] (story_view.js:617)

We try to rollback to previous version but it doesn't help.

Thank you very much for your help.

**Comment by Laffarli** [comment]
If I rollback to commit cd4c2ab5d83ceb123036c596f802a2f6ad1ad492 (just before pusher...) it works again.
Is it related to the fact that I do not use pusher?
Can we avoid using pusher? If yes, how ?

**Comment by talyssonoc** [comment]
Hello, @Laffarli, thanks for reporting the issue.

It's happening due to the absence of this https://github.com/Codeminer42/cm42-central/blob/master/.env.sample#L24 env var in your  `.env`. This should make it stop breaking.

The problem is that we use Pusher for live updates now, so if we don't use pusher nothing will _break_ but the live update (cross-tab and cross-client) won't work because we rely on Pusher for that. We used to do it with polling but it was causing major performance issues, so we're open to receiving a PR to fallback to long polling in case pusher is not available in the environment.
