### ISSUE TITLE
Unable to upload a file when creating a story

### ISSUE THREAD

**Issue by daniloisr** [Codeminer42/cm42-central#92]
from Rafael Gibim:

> Não estou conseguindo criar uma nova story com attachment. Após anexar o arquivo, o botão de "Save" não é liberado mesmo após o fim do upload
workaround que usei foi criar uma story, depois editei ela e coloquei o anexo normalmente

**Comment by wkurosawa** [comment]
@CaiqueMitsuoka I've been looking into this bug and looks like `this.uploadInProgress` is set to **true** on `attachmentStart` function and is only set to **false** on `saveEdit` (which, if the story is new it's not called).

Do you think we can set `this.uploadInProgress` to **false** on `attachmentDone`? 
Also looks logical that when attachment process is done it's not uploading anymore. 

And maybe change the name `disableControlButtons` since it also enable buttons. 

```javascript

  attachmentDone: function(event) {
    if (!this.model.isNew()) {
      this.saveEdit(event, true);
    }
    this.uploadInProgress = false;
    this.disableControlButtons();
  },
```
